---
name: CI

on: [push, pull_request]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: Install dependencies
      run: conda env update -f environment.yaml -n base
    - name: Run unit tests
      run: python -m pytest -v