---
name: Lint

on:
  pull_request:
  push:
    branches:
    - main

env:
  PYTHON_VERSION: 3.8

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Run black
      run: |
        python -m pip install "black==20.8b1"
        black --version
        black -S --check --diff *.py
    - name: Run flake8
      run: |
        python -m pip install "flake8==3.8.*"
        flake8 --version
        flake8 *.py
