---
name: Lint

on:
  pull_request:
  push:
    branches:
    - main

env:
  PYTHON_VERSION: 3.8

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Run black
      run: |
        python -m pip install "black==20.8b1"
        black --version
        black -S --check --diff *.py
    - name: flake8 Lint
      uses: py-actions/flake8@v1
      with:
        ignore: "E501"
        ignore: "W503"
        max-line-length: "100"